participants_matrix:
  el:
    - el_type: geth
      el_image: ethpandaops/geth:lightclient-prague-devnet-1-37c4b03
  cl:
    - cl_type: lighthouse
      cl_image: ethpandaops/lighthouse:electra-devnet-1-ba28217
    - cl_type: teku
      cl_image: ethpandaops/teku:master-2d2d17b
    - cl_type: nimbus
      cl_image: ethpandaops/nimbus-eth2:unstable-minimal-c0fc0f4
    - cl_type: grandine
      cl_image: ethpandaops/grandine:electra-minimal-b7bae2c
network_params:
  electra_fork_epoch: 5
  min_validator_withdrawability_delay: 1
  shard_committee_period: 1
  preset: minimal
additional_services:
  - dora
